export { default as DLabel } from './Label.vue'
export { default as DCheckbox } from './Checkbox.vue'
export { default as DInput } from './Input.vue'
export { default as DCombobox } from './Combobox.vue'
export { default as DSwitch } from './Switch.vue'